Pipeline2 18 create branch
liatrio/libotrio-1.0 pull request #62
Opened 2019-01-24 01:09 UTC by JGuzman4

2019-01-24 01:31 UTC, jbankes requested changes
changes requested mentioned in slack

2019-01-24 01:34 UTC, jbankes commented on libotrio.js
> +  clientSigningSecret: process.env.SLACK_VERIFICATION_TOKEN,
is this going to cause a problem for local debugging that we are aware of?

2019-01-24 16:25 UTC, JGuzman4 commented on libotrio.js
> +  clientSigningSecret: process.env.SLACK_VERIFICATION_TOKEN,
Not sure. I believe that variable will just be set to null like it was before

2019-01-26 02:13 UTC, jbankes approved these changes

2019-01-26 02:15 UTC, jbankes submitted a review, later dismissed
Fulfilled all asks. Adds Jira ticket grabbing to Libotrio. LGTM

2019-02-01 18:21 UTC, Nelsonater submitted a review, later dismissed
Looks good to me

2019-02-01 18:25 UTC, Nelsonater approved these changes
Version bump. Looks good

2019-02-01 18:25 UTC, merged